### ISSUE TITLE
Have a problem with login: hello@gmail.com/123456

### ISSUE THREAD

**Issue by ptizaezhik** [datainsider-co/rocket-bi#101]
Hello!

I have installed rocket.bi in according to https://github.com/datainsider-co/rocket-bi/blob/main/README.md

But I have a problem with login: hello@gmail.com/123456
"Incorrect email or password"

How to login the first time?

**Comment by tvc12** [comment]
hi @ptizaezhik
1. Please ensure all services are running. BI services need a few minutes for warmup.
2. Please inspect the login request and show the response here.

**Comment by ptizaezhik** [comment]
>     2. Please inspect the login request and show the response here.

502 Bad Gateway

HTTP/1.1 502 Bad Gateway
Server: nginx/1.25.1
Date: Thu, 28 Dec 2023 06:09:46 GMT
Content-Type: text/html
Content-Length: 157
Connection: keep-alive


Rocket is running in Docker on Windows10.
All containers are running.

**Comment by ptizaezhik** [comment]
Will try reinstall.
On another comp its OK.

**Comment by tvc12** [comment]
Hi @ptizaezhik ,
1. Ensure bi service is running by cmd:
```sh
docker ps
```
and find name `rocket-bi-server`
2. If rocket-bi-sever is running, i think problem in nginx. Try cmd for test nginx
```bash
docker exec rocket-nginx nginx -t

# nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
# nginx: configuration file /etc/nginx/nginx.conf test is successful
```
Then reload nginx by cmd
```bash
docker exec rocket-nginx nginx -s reload
```
Check again!

**Comment by tvc12** [comment]
Hi @ptizaezhik, Is it working now?

**Comment by ptizaezhik** [comment]
> Hi @ptizaezhik, Is it working now?

C:\Users\HAV>docker exec rocket-nginx nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

C:\Users\HAV>docker exec rocket-nginx nginx -s reload

But no effect.

I will use another computer, there is ok. 
Thank you.

**Comment by harshith-bolar-rapido** [comment]
> Hi [@ptizaezhik](https://github.com/ptizaezhik) ,
> 
> 1. Ensure bi service is running by cmd:
> 
> docker ps
> and find name `rocket-bi-server` 2. If rocket-bi-sever is running, i think problem in nginx. Try cmd for test nginx
> 
> docker exec rocket-nginx nginx -t
> 
> # nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
> # nginx: configuration file /etc/nginx/nginx.conf test is successful
> Then reload nginx by cmd
> 
> docker exec rocket-nginx nginx -s reload
> Check again!

The readme doesn't say anything about `rocket-nginx`. Where is this coming from?

**Comment by tvc12** [comment]
hi @harshith-bolar-rapido,
1. Deployment file is here https://github.com/datainsider-co/rocket-bi/blob/v23.11.30/docker/docker-compose.yml
2. That is a syntax of docker for reload nginx, you can check in deployment file
