### ISSUE TITLE
Display wrong date range in Change date function

### ISSUE THREAD

**Issue by hahoang1911** [datainsider-co/rocket-bi#43]
- The date range of **Week of Month** should be changed to **Week of Year**

![image](https://user-images.githubusercontent.com/113515551/196657175-9d4df63b-cf36-413a-8e60-7b08d29324f4.png)

- The date range of **Day of Month** displays not enough days

![image](https://user-images.githubusercontent.com/113515551/196657511-bfe668c6-dd61-47bc-b460-da234094ac37.png)

**Comment by dnsang** [comment]
noted. 
@HaoCooky please check.
