### ISSUE TITLE
Not able to connect to clickhouse Database

### ISSUE THREAD

**Issue by hmnth1** [datainsider-co/rocket-bi#68]
I have installed both clickhouse server and rocket bi in the same server.
Changed configuration as specified 
But In organization setting it is showing status as Unhealthy and not able to connect to Database

I am accessing Rocket BI remotely. Not through localhost:5050.

![image](https://user-images.githubusercontent.com/29772989/236113654-7cd7c20b-8b41-4e1a-b2df-0217b0d4cae5.png)

**Comment by dnsang** [comment]
Hi @hmnth1 ,
Could you please paste here your config? 
It would be great if you could send the log file as well.

**Comment by dnsang** [comment]
resolved.
