### ISSUE TITLE
Kết quả trên dashboard và file excel tải về đang không đồng nhất.

### ISSUE THREAD

**Issue by hongnextpay** [datainsider-co/rocket-bi#69]
Lúc filter trên dashboard thì danh sách ở bảng có trả về dữ liệu đúng ạ.
![image](https://github.com/datainsider-co/rocket-bi/assets/137493463/9626bd6c-a49e-47ad-836b-e21b0ffb13b0)

File excel download từ dashboard (với các filter như trên) mở ra thì trống trơn ạ.

Anh xem hỗ trợ em nhé ạ.
![image](https://github.com/datainsider-co/rocket-bi/assets/137493463/feaffb47-3f6d-4a68-a303-8c6713a0db46)

**Comment by dnsang** [comment]
Done. Please upgrade to version 2.0.4.
