### ISSUE TITLE
Xin cấp lại password cho 1 user

### ISSUE THREAD

**Issue by hongnextpay** [datainsider-co/rocket-bi#70]
Bên em có user hanhntn@nextpay.vn quên pw. Khi sử dụng chức năng Forgot password thì báo là không nhận được mã code send về email.
Em tự test bằng tài khoản của mình thì vẫn nhận được mã code.
Mà do hanhntn@nextpay.vn không ở HN nên em hơi khó để support.
Bên anh có thể update trong database password của tài khoản đó và gửi cho em được không ạ?
Em cảm ơn ạ.

**Comment by andy1912** [comment]
Admin có thể reset password cho thành viên nhé Hồng.
