### ISSUE TITLE
Vẫn sai khi download file excel ạ

### ISSUE THREAD

**Issue by hongnextpay** [datainsider-co/rocket-bi#72]
![image](https://github.com/datainsider-co/rocket-bi/assets/137493463/85af98e9-cdb2-42a5-ad05-8bbb4f475e8b)
Như ảnh em gửi thì hiển thị dashboard 1 kiểu nhưng download về lại ra giá trị khác.
Chỉ bị lỗi với file .xlsx, file .csv thì oke ạ.
Các anh check giúp em với nhé.

**Comment by dnsang** [comment]
Fixed. Release 1.4.9
