### ISSUE TITLE
Lỗi khi load dữ liệu với source từ Google sheet

### ISSUE THREAD

**Issue by hongnextpay** [datainsider-co/rocket-bi#74]
File ggsheet của em có hơn 500k bản ghi
![image](https://github.com/datainsider-co/rocket-bi/assets/137493463/d1f24237-91c4-4778-b78c-53345861005e)
Khi load vào DI thì dữ liệu không được đầy đủ, chỉ được 100-200k bản ghi. 
Và em cho load đi load lại nhiều lần thì mỗi lần lại có số lượng bản ghi khác nhau.
Các anh fix giúp em ạ.
![image](https://github.com/datainsider-co/rocket-bi/assets/137493463/36037aef-0584-4536-8ce1-86c7113d5be5)

**Comment by hongnextpay** [comment]
Anh ưu tiên xử lý bug này giúp em với ạ. Em cảm ơn team mình ạ.

**Comment by dnsang** [comment]
Please check release 1.4.9
