### ISSUE TITLE
Lỗi khi query

### ISSUE THREAD

**Issue by hongnextpay** [datainsider-co/rocket-bi#75]
Chi tiết lỗi khi query em gửi kèm video ạ.
https://drive.google.com/file/d/1gY_vdFG0hFd-paCR7J5l-5SuKK0hnMcT/view?usp=sharing
Ví dụ dùng query = thì không được, dùng >= thì được, dùng round thì được.
Team anh check giúp em bug này với ạ.

**Comment by dnsang** [comment]
Đừng so sánh các số float/double trực tiếp e nhé.
