### ISSUE TITLE
Chart Cross Filtering 

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#89]
Hi,
I want to implement the chart cross filtering in my dashboards. I want to know whether the below actions are possible using [rocket.bi](http://rocket.bi/), If it is then Can you please guide us?
1. When I interact with one chart and apply that interaction as a filter to other charts in the report. 
2. Clicking on one or more dimension values in the chart is possible using rocket bi?

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan
1. Of course, you can set up a filter that can be applied to others using a step-by-step process:
  + Add Filter
  + Edit chart -> choose chart control -> select dimension values you want to filter.
  
[demo_add_filter.webm](https://github.com/datainsider-co/rocket-bi/assets/35712888/7bc88ac0-f824-4fe8-8601-57f510e7bcbc)

2. Yep, you can choose dimension of chart as a filter
