### ISSUE TITLE
Number Chart with previous day and today comparison.

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#92]
Hi,
A numerical chart comparing the total orders placed the previous day to today along with the percentage difference. 
In the number chart's Default Date Range settings, I selected **Today** as the Default range and **Previous Period** as the Comparsion setting. The order count from yesterday's percentage difference value is displayed in the result.
![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/d317bec9-fe35-4008-b32e-5132651abdd9)

Nevertheless, When I choose the **custom** as an Date Range option and the **Previous Period** as an comparison setting. It displays the percentage of today's orders which is the expected result.
![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/fbaca329-70ba-4432-8244-e26667b57f5c)

As an example, let's say there were 5 orders placed today and 15 orders were placed the day before. I would want to see the percentage shown as -66.66%. Still, it displays +66.66%. Can this be accomplished using the data range of today?

**Comment by tvc12** [comment]
HI @Nandhini-Kumaresan,
Can you tell me about the warehouse you use? ClickHouse or MySQL?

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12 ,
I am using MySQL.
