### ISSUE TITLE
On Date Histogram, Half yearly option is not available.

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#93]
Hi,
I would want to display the data records from the last six months on a chart. Is it possible to give the Date Histogram a half-yearly option similar to the **Quarter of year** and **Year** options? For your information, I have included a screenshot.
![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/ab929b25-a3ed-4d07-a160-1b2a47b5228a)

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan,
Haft yearly option is unavailable in RocketBi. Btw, you can use add calculated instead of.

**Comment by tvc12** [comment]
If you want to help, you can open discussion. We will help you quickly.

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12,
Can you please help me with a formula to calculate Half-yearly?
![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/6d53e9fc-66e8-4f91-bac1-530e778985ac)
 `if(MONTH(toDate([created_at])) > MONTH(today()) - 6 , '1' , '0')`
I used this formula to check whether the date is in last 6 months.

**Comment by tvc12** [comment]
You can use query for haft yearly:
```sql
CONCAT(YEAR(your_date_column), 
              CASE 
                WHEN MONTH(your_date_column) BETWEEN 1 AND 6 THEN '-H1' 
                ELSE '-H2' 
              END
       ) AS formatted_half_year
```

Example:

![image](https://github.com/datainsider-co/rocket-bi/assets/35712888/8784c173-5a33-40f2-a079-52923ca770e3)

**Comment by Nandhini-Kumaresan** [comment]
@tvc12 Thanks for your support. It's working fine.
