### ISSUE TITLE
Connect many Google Analytics with several email addresses

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#97]
Is it possible to add many Google Analytics accounts with several email addresses on same bi?
For example, I've included Google Analytics data source of _xyz@gmail.com_. I now wish to add the Google Analytics account of _abc@gmail.com_ without deleting the previous one.

**Comment by tvc12** [comment]
Of course, you can add unlimited Google Analytics data sources with different accounts. Furthermore, you can add up to **25** data sources same the account. Check out the document [here](https://developers.google.com/analytics/devguides/reporting/core/v4/authorization)
![image](https://github.com/datainsider-co/rocket-bi/assets/35712888/d2382953-7148-41cb-b4ac-48444046ce41)

**Comment by Nandhini-Kumaresan** [comment]
Should I change the client ID and secret for additional accounts in `rocket-bi-server/conf/product.conf` and `rocket-bi-web/public/config/production.js` files each time I add a new datasource for a different account? Account with _xyz@gmail.com_ has already been added. However, when I attempt to add an _abc@gmail.com_ GA4 account, The cloud google project name which i added on the code appears on the popup.  Also, it isn't retrieving the GA4 accounts of _abc@gmail.com_. 
For your reference attached the screenshot.

![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/0c2551e7-ec85-49ea-b07e-bc0b5922d706)

**Comment by Nandhini-Kumaresan** [comment]
We want to configure multiple client_id because we are planning to configure for multiple customers on the single rocket bi installation. Also, Does rocket bi support multi-tenant?

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan,
1. We only support one client ID in a Rocket BI instance.
2. In the open-source version (OSS), we support online single-tenant deployment. However, with an on-premise license, you can achieve multi-tenancy. I believe you should consider becoming a third-party partner or reseller for my company. We can support you in deployment, bug fixes, feature requests quickly

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12 ,
Thank you for the information.

**Comment by tvc12** [comment]
We welcome to [contact@datainsider.co](mailto:contact@datainsider.co).
I will mark the issue to completed.
Thank you
